services:
  mysql:
    image: mysql:8.0
    container_name: xj-selenium-agri-mysql
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-time-zone=+08:00
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: xj_selenium_agri
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
